services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nikama_app
    restart: unless-stopped
    working_dir: /var/www

    ports:
      - "8000:80"

    volumes:
      - .:/var/www

    env_file:
      - .env

    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000

    networks:
      - nikama

networks:
  nikama:
    driver: bridge